version: '2'

services:
  web:
    image: drupal:8.9
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    depends_on: 
      - db
  db:
    image: postgres:12.6
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: